-- Criando Banco de dados

create database BD_Empresa
use BD_Empresa

-- Criando Tabela Exercício

CREATE TABLE Tabela_Departamento (
CODDEPARTAMENTO INT NOT NULL,
NOME_DEPARTAMENTO VARCHAR(20) NOT NULL,
RAMAL CHAR(4),
LOCALIZACAO CHAR(9)
);

-- Testando Tabela

describe Tabela_departamento;
select * from Tabela_departamento;

-- Inserindo dado teste

insert into tabela_departamento
(CODDEPARTAMENTO, NOME_DEPARTAMENTO, RAMAL, LOCALIZACAO)
values
(1, 'VENDAS', '8501', 'TÉRREO')

-- Repetindo exercício

create DATABASE BD_LOJA;
use BD_LOJA;

create table PRODUTO (
CODIGO INT NOT NULL,
NOME VARCHAR(20) NOT NULL,
PRECO DECIMAL(10,2) NOT NULL,
QTD INT
);
DESCRIBE PRODUTO;

create table PEDIDO (
NUM int NOT NULL,
VALOR_TOTAL DECIMAL (10,2) NOT NULL,
NF INT NOT NULL
);
DESCRIBE PEDIDO;

create table CLIENTE (
CPF INT (11),
NOME VARCHAR (40) NOT NULL,
CELULAR INT (11)
);
DESCRIBE CLIENTE;

create table FUNCIONARIO (
MATR int,
NOME VARCHAR (40) NOT NULL,
CARGO VARCHAR (20)
);
DESCRIBE FUNCIONARIO;

-- Aula 6
-- Recriando tabela cadfun

CREATE DATABASE bd_virtual
use bd_virtual

CREATE TABLE cadfun (
CODFUN INT NOT NULL,
NOME VARCHAR(40) NOT NULL,
DEPTO CHAR(2),
FUNCAO CHAR(20),
SALARIO DECIMAL(10, 2)
);
-- Reinserindo dados pra ficar mais facil

INSERT INTO cadfun
(CODFUN, NOME, DEPTO, FUNCAO, SALARIO)
VALUES
(12, 'CARLOS ALBERTO', '3' , 'VENDEDOR' , 1530.00);  

INSERT INTO cadfun
(CODFUN, NOME, DEPTO, FUNCAO, SALARIO)
VALUES
(13, 'MARIA CLARA', '4' , 'ATENDENTE' , 1960.00); 

INSERT INTO cadfun
(CODFUN, NOME, DEPTO, FUNCAO, SALARIO)
VALUES
(14, 'JOÃO MANOEL', '1' , 'GERENTE' , 4790.00); 

INSERT INTO cadfun
(CODFUN, NOME, DEPTO, FUNCAO, SALARIO)
VALUES
(15, 'MANOEL CARLOS', '4' , 'DIRETOR' , 8500.00); 

INSERT INTO cadfun
(CODFUN, NOME, DEPTO, FUNCAO, SALARIO)
VALUES
(16, 'SANDRA SANTOS', '3' , 'VENDEDOR' , 1530.00); 

INSERT INTO cadfun
(CODFUN, NOME, DEPTO, FUNCAO, SALARIO)
VALUES
(17, 'LUCIA BRITO', '2' , 'ATENDENTE' , 1850.00); 

INSERT INTO cadfun
(CODFUN, NOME, DEPTO, FUNCAO, SALARIO)
VALUES
(18, 'CAMILA NOGUEIRA', '5' , 'REEPCIONISTA' , 2320.00);

-- Exercício seleção

Select NOME, FUNCAO FROM cadfun;

SELECT DISTINCT DEPTO FROM CADFUN;

SELECT NOME, SALARIO FROM cadfun
ORDER BY NOME;

SELECT NOME, CODFUN FROM cadfun
WHERE DEPTO = '3'
ORDER BY NOME;

SELECT * FROM cadfun
WHERE FUNCAO = 'DIRETOR';

-- Atividade Parte 1 - aula 6

-- 1) Funcionarios dpto 4
SELECT CODFUN, NOME FROM cadfun;
WHERE DEPTO = '4'

-- 2) Salarios distintos
SELECT DISTINCT SALARIO FROM cadfun;

-- 3) Nome e departamento ordem alfabetica
SELECT NOME, DEPTO FROM cadfun
ORDER BY DEPTO;

-- 4) Analistas do menor para o maior salario
SELECT * from cadfun
WHERE FUNCAO = 'ANALISTA'
ORDER BY SALARIO;
